name: Label workflow
on: 
  pull_request:
    types:
      - labeled

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  label-review-completed:
    if: github.event.label.name == 'review-completed' && github.event.sender.login != github.event.pull_request.user.login
    runs-on: ubuntu-latest
    concurrency:
      group: label-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v5

      - name: Run my script
        run: echo "Run my script when review-completed label is added by a reviewer"

  remove-label-job-added-by-author:
    if: github.event.label.name == 'review-completed' && github.event.sender.login == github.event.pull_request.user.login
    runs-on: ubuntu-latest
    concurrency:
      group: label-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Remove review-completed label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'review-completed'
            })

      - name: Fail workflow
        run: exit 1

